
const ALL_NOTES_REQUEST="ALL_NOTES_REQUEST"
const ADD_NOTES_REQUEST="ADD_NOTES_REQUEST"
const EDIT_NOTES_REQUEST="EDIT_NOTES_REQUEST"
const DELETE_NOTES_REQUEST="DELETE_NOTES_REQUEST"
const MY_NOTES_REQUEST="MY_NOTES_REQUEST"

const ALL_NOTES_FAILURE="ALL_NOTES_FAILURE"
const ADD_NOTES_FAILURE="ADD_NOTES_FAILURE"
const EDIT_NOTES_FAILURE="EDIT_NOTES_FAILURE"
const DELETE_NOTES_FAILURE="DELETE_NOTES_FAILURE"
const MY_NOTES_FAILURE="MY_NOTES_FAILURE"

const ALL_NOTES_SUCCESS="ALL_NOTES_SUCCESS"
const MY_NOTES_SUCCESS="MY_NOTES_SUCCESS"
const ADD_NOTES_SUCCESS="ADD_NOTES_SUCCESS"
const EDIT_NOTES_SUCCESS="EDIT_NOTES_SUCCESS"
const DELETE_NOTES_SUCCESS="DELETE_NOTES_SUCCESS"

const SET_REDIRECT="SET_REDIRECT"
const RESET_REDIRECT="RESET_REDIRECT"


export{ALL_NOTES_SUCCESS,
    MY_NOTES_SUCCESS,ADD_NOTES_SUCCESS,EDIT_NOTES_SUCCESS
    ,DELETE_NOTES_SUCCESS,ALL_NOTES_REQUEST,ALL_NOTES_FAILURE,ADD_NOTES_REQUEST,ADD_NOTES_FAILURE,MY_NOTES_REQUEST,MY_NOTES_FAILURE,
EDIT_NOTES_REQUEST,EDIT_NOTES_FAILURE,DELETE_NOTES_REQUEST,DELETE_NOTES_FAILURE,SET_REDIRECT,RESET_REDIRECT}
